# vars/environments/production.yml - Production-specific overrides
---
# ===========================================
# PRODUCTION ENVIRONMENT CONFIGURATION
# ===========================================

# Connection settings
aap_public_url: "https://aap.yourdomain.com"
aap_admin_user: "admin"
aap_verify_ssl: true

# Environment
environment: "production"

# Enhanced project configuration for production
projects:
  - name: "Demo Playbooks"
    description: "Sample playbooks for testing infrastructure"
    scm_type: "git"
    scm_url: "https://github.com/ansible/ansible-examples.git"
    scm_branch: "master"
    scm_clean: true
    scm_update_on_launch: false  # Disable auto-update in production
    scm_update_cache_timeout: 3600
    timeout: 600
    
  - name: "Infrastructure Playbooks"
    description: "Production infrastructure management playbooks"
    scm_type: "git"
    scm_url: "https://github.com/your-org/infrastructure-playbooks.git"
    scm_branch: "main"
    credential: "Git SCM Credential"
    scm_clean: true
    scm_update_on_launch: false
    timeout: 900

# Enhanced job templates for production
job_templates:
  - name: "Ping All Managed Nodes"
    description: "Test connectivity to all managed nodes"
    project: "Demo Playbooks"
    playbook: "ping.yml"
    inventory: "Managed Infrastructure"
    credentials: ["Managed Nodes SSH Key"]
    execution_environment: "Infrastructure EE"
    timeout: 300
    verbosity: 0  # Reduced verbosity for production
    allow_simultaneous: false
    
  - name: "System Updates - Production"
    description: "Apply system updates to production managed nodes"
    project: "Infrastructure Playbooks"
    playbook: "system_updates.yml" 
    inventory: "Managed Infrastructure"
    credentials: ["Managed Nodes SSH Key", "Vault Credential"]
    execution_environment: "Infrastructure EE"
    timeout: 3600  # Extended timeout for production
    become_enabled: true
    ask_limit_on_launch: true
    ask_variables_on_launch: true
    extra_vars:
      reboot_after_update: false
      maintenance_window: true
    survey_enabled: true
    
  - name: "Security Hardening"
    description: "Apply security hardening to managed nodes"
    project: "Infrastructure Playbooks"
    playbook: "security_hardening.yml"
    inventory: "Managed Infrastructure"
    credentials: ["Managed Nodes SSH Key", "Vault Credential"]
    execution_environment: "Security EE"
    timeout: 2400
    become_enabled: true
    ask_limit_on_launch: true
    ask_tags_on_launch: true

# Production notification configuration
notification_templates:
  - name: "Email Notifications"
    description: "Email notifications for job status"
    type: "email"
    configuration:
      host: "smtp.yourdomain.com"
      port: 587
      username: "{{ smtp_username }}"
      password: "{{ smtp_password }}"
      sender: "aap-production@yourdomain.com"
      recipients:
        - "sre-team@yourdomain.com"
        - "infra-alerts@yourdomain.com"
      use_tls: true
      
  - name: "Slack Notifications"
    description: "Slack notifications for critical alerts"
    type: "slack"
    configuration:
      token: "{{ slack_token }}"
      channels:
        - "#infrastructure-alerts"
      username: "AAP-Production"

# Production-specific settings
run_validation: false  # Skip validation in production
max_retries: 5
retry_delay: 10