# vars/defaults.yml - Simplified default values for POC
---
# ===========================================
# DEFAULT CONFIGURATION VALUES
# ===========================================

# Default organization (using built-in Default org for simplicity)
default_organization: "Default"

# ===========================================
# CREDENTIAL DEFAULTS
# ===========================================

# SSH credential for managed nodes
managed_nodes_credential:
  name: "Managed Nodes SSH Key"
  description: "SSH key for accessing managed nodes via jump host"
  username: "ec2-user"
  credential_type: "Machine"

# ===========================================
# EXECUTION ENVIRONMENT DEFAULTS
# ===========================================

# Single execution environment for simplicity
default_execution_environment:
  name: "Default EE"
  description: "Default execution environment for POC"
  image: "quay.io/ansible/automation-hub-ee:latest"
  pull: "missing"

# ===========================================
# PROJECT DEFAULTS
# ===========================================

# Demo project using public repository
demo_project:
  name: "Demo Playbooks"
  description: "Sample playbooks for POC testing"
  scm_type: "git"
  scm_url: "https://github.com/ansible/ansible-examples.git"
  scm_branch: "master"
  scm_clean: true
  scm_update_on_launch: true
  timeout: 600

# ===========================================
# INVENTORY DEFAULTS
# ===========================================

# Single inventory for managed infrastructure
default_inventory:
  name: "Managed Infrastructure"
  description: "POC managed nodes accessible via jump host"
  variables:
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

# Default group for managed nodes
managed_group:
  name: "managed_environment"
  description: "All managed nodes for POC"
  variables:
    environment: "poc"
    node_type: "managed"

# ===========================================
# JOB TEMPLATE DEFAULTS
# ===========================================

# Job templates for POC
essential_job_templates:
  - name: "Ping All Managed Nodes"
    description: "Test connectivity to all managed nodes"
    playbook: "lamp_simple/roles/common/tasks/main.yml"
    timeout: 300
    verbosity: 1
    become_enabled: false
    allow_simultaneous: true
    
  - name: "System Information"
    description: "Gather basic system information from managed nodes"
    playbook: "lamp_simple/site.yml"
    timeout: 600
    verbosity: 1
    become_enabled: false
    ask_limit_on_launch: true
    extra_vars:
      gather_facts: true
      
  - name: "Run Ad-hoc Commands"
    description: "Run simple commands on managed nodes"
    playbook: "lamp_simple/roles/common/tasks/main.yml"
    timeout: 300
    verbosity: 2
    become_enabled: true
    ask_limit_on_launch: true
    ask_variables_on_launch: true

# ===========================================
# TIMEOUT AND PERFORMANCE SETTINGS
# ===========================================

# Timeouts
default_timeouts:
  project_sync: 300
  job_execution: 600
  validation: 300

# Verbosity levels
verbosity_levels:
  minimal: 0
  normal: 1
  verbose: 2
  debug: 3

# Default verbosity for POC (normal)
default_verbosity: 1
