# templates/aap_install_inventory.tpl
# AAP 2.5 Installation Inventory
# This inventory file is used by the AAP installer running on the controller node
# Generated by Terraform on ${timestamp()}

[automationcontroller]
${aap_private_ip} ansible_connection=local

[execution_nodes]
${exec_private_ip} ansible_host=${exec_private_ip} ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/.ssh/id_rsa

[automationcontroller:vars]
# Controller node is localhost since installer runs on this node
node_type=control
peers=execution_nodes

[execution_nodes:vars]
node_type=execution

[all:vars]
# AAP Installation Configuration
admin_password=${aap_admin_password}
pg_host=''
pg_port=5432
pg_database='awx'
pg_username='awx'
pg_password='${pg_password}'
pg_sslmode='prefer'

# Use embedded PostgreSQL database on controller
postgresql_admin_username='postgres'
postgresql_admin_password='${postgresql_admin_password}'

# Web server configuration  
nginx_tls_cert=/etc/ssl/certs/nginx.crt
nginx_tls_key=/etc/ssl/private/nginx.key

# Registry configuration (Red Hat registry access)
%{ if registry_username != "" ~}
registry_url='registry.redhat.io'
registry_username='${registry_username}'
registry_password='${registry_password}'
%{ endif ~}

# Automation Hub configuration (optional - disabled by default)
# automationhub_admin_password=${automationhub_admin_password}
# automationhub_pg_host=''
# automationhub_pg_port=5432
# automationhub_pg_database='automationhub'
# automationhub_pg_username='automationhub'
# automationhub_pg_password=${automationhub_pg_password}

# SSO configuration (optional - disabled by default)
# sso_admin_password=${sso_admin_password}

# General settings
routable_hostname=${aap_fqdn}
receptor_listener_port=27199

# Execution environment settings
ee_from_hub_only=false
ee_auto_update=true

# Job isolation and performance
job_execution_isolation=true
isolated_groups_enabled=false

# Logging configuration
log_aggregator_enabled=false
log_aggregator_level=INFO

# Backup configuration
backup_dir=/var/backups/aap

# Performance tuning for t3.2xlarge instance
# Adjust based on your instance size and workload
max_concurrent_jobs=10
job_event_buffer_size=30000

# Database connection pool settings
pg_max_connections=200
pg_shared_buffers=256MB

# LDAP configuration (disabled by default)
# Uncomment and configure for LDAP integration
# auth_ldap_server_uri='ldaps://ldap.example.com'
# auth_ldap_bind_dn='cn=admin,dc=example,dc=com'
# auth_ldap_bind_password='password'
# auth_ldap_user_search_base_dn='ou=users,dc=example,dc=com'
# auth_ldap_group_search_base_dn='ou=groups,dc=example,dc=com'

# Custom CA certificate (if needed)
# custom_ca_cert=/path/to/ca.crt

# Session configuration
session_cookie_age=86400
csrf_cookie_secure=True
session_cookie_secure=True

# Nginx configuration
nginx_disable_https_redirect=false
nginx_disable_hsts=false

# Redis configuration (for caching and sessions)
redis_host=127.0.0.1
redis_port=6379

# Disable unused services for single-node installation
automationhub_disable_https=false
automationhub_disable_hsts=false