---
# Ansible Inventory for AAP 2.5 POC Infrastructure
# Generated by Terraform - Simplified for POC

all:
  children:
    # Administrative Access Point
    bastion:
      hosts:
        ${name_prefix}-bastion:
          ansible_host: ${bastion_public_ip}
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ${ops_key_path}
          ansible_ssh_common_args: '-F inventory/ssh_config'
          role: bastion
          
    # AAP Infrastructure 
    aap_infrastructure:
      children:
        aap_hosts:
          hosts:
            ${name_prefix}-aap:
              ansible_host: aap
              ansible_ssh_common_args: '-F inventory/ssh_config'
              aap_url: https://${aap_fqdn}
              role: aap-controller
              
        execution_nodes:
          hosts:
            ${name_prefix}-exec:
              ansible_host: exec
              ansible_ssh_common_args: '-F inventory/ssh_config'
              role: execution-node
              
    # Jump Host (Network Bridge)
    jump_hosts:
      hosts:
        ${name_prefix}-jump:
          ansible_host: jump
          ansible_ssh_common_args: '-F inventory/ssh_config'
          aap_interface_ip: ${jump_aap_ip}
          managed_interface_ip: ${jump_managed_ip}
          role: jump-host
          
    # Managed Infrastructure (Automation Targets)
    managed_nodes:
      hosts:
%{ for i, node in managed_nodes ~}
        ${node.name}:
          ansible_host: managed-${i}
          ansible_ssh_common_args: '-F inventory/ssh_config'
          role: managed-node
%{ endfor ~}
          
  vars:
    # Global Configuration
    ansible_python_interpreter: /usr/bin/python3
    
    # Network Information
    vpc_cidr: ${vpc_cidr}
    
    # AAP Configuration
    aap_url: https://${aap_fqdn}
    aap_private_ip: ${aap_private_ip}
    
    # SSH Keys
    aap_ssh_key: ${aap_key_path}
    ops_ssh_key: ${ops_key_path}
    
    # Jump Host Configuration
    jump_host_ip: ${jump_aap_ip}

# Group Variables
aap_infrastructure:
  vars:
    # Access via bastion for admin tasks
    access_method: bastion
    
managed_nodes:
  vars:
    # Access via jump host for automation
    access_method: jump_host
    automation_user: ec2-user