# templates/aap_install_inventory.tpl
# AAP 2.5 Installation Inventory
# This inventory file is used by the AAP installer running on the controller node
# Generated by Terraform on ${timestamp()}

[automationgateway]
${aap_private_ip}

[automationcontroller]
${aap_private_ip}

[automationhub]
${aap_private_ip}

[automationeda]
${aap_private_ip}

[database]
${aap_private_ip}

[all:vars]
ansible_connection=local

# Use embedded PostgreSQL database on controller
postgresql_admin_username='postgres'
postgresql_admin_password='${postgresql_admin_password}'

registry_username='${registry_username}'
registry_password='${registry_password}'

redis_mode=standalone

gateway_admin_password=${aap_admin_password}
gateway_pg_host=${aap_private_ip}
gateway_pg_password=${aap_admin_password}

controller_admin_password=${aap_admin_password}
controller_pg_host=${aap_private_ip}
controller_pg_password=${aap_admin_password}
controller_percent_memory_capacity=0.5

hub_admin_password=${aap_admin_password}
hub_pg_host=${aap_private_ip}
hub_pg_password=${aap_admin_password}
hub_seed_collections=false

eda_admin_password=${aap_admin_password}
eda_pg_host=${aap_private_ip}
eda_pg_password=${aap_admin_password}

[execution_nodes]
${exec_private_ip} ansible_host=${exec_private_ip} ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/.ssh/id_rsa

