# infrastructure/templates/aap_controller_vars.tpl
# AAP Controller Configuration Variables
# Generated by Terraform - Auto-populated with infrastructure details

# ===========================================
# CONTROLLER CONNECTION SETTINGS  
# ===========================================

# AAP Controller URL (from terraform)
aap_public_url: "https://${aap_fqdn}"

# Admin credentials (from terraform.tfvars)
aap_admin_user: "admin"
aap_admin_password: "${aap_admin_password}"

# SSL verification (false for POC)
aap_verify_ssl: false

# ===========================================
# INFRASTRUCTURE DETAILS (Auto-populated)
# ===========================================

# Organization to use (Default for simplicity)
organization_name: "Default"

# Project repository (actual project)
project_name: "AAP SSH Jump POC"
project_scm_url: "https://github.com/redhat-telco-adoption/aap-ssh-jump-poc.git"
project_scm_branch: "main"

# SSH credential configuration
ssh_credential_name: "Managed Nodes SSH Key"
ssh_username: "ec2-user"

# Jump host configuration (from terraform)
jump_host_ip: "${jump_aap_ip}"

# Managed nodes (from terraform)
managed_hosts:
%{ for i, instance in managed_instances ~}
  - name: "managed-node-${i}"
    ansible_host: "${instance.private_ip}"
    private_ip: "${instance.private_ip}"
%{ endfor ~}

# ===========================================
# JOB TEMPLATES CONFIGURATION
# ===========================================

job_templates:
  - name: "Ping All Managed Nodes"
    description: "Test connectivity to managed nodes using ping.yml"
    playbook: "ansible/playbooks/ping.yml"
    timeout: 300
    verbosity: 1
    
  - name: "System Information"
    description: "Gather system information using system_info.yml"
    playbook: "ansible/playbooks/system_info.yml"
    timeout: 600
    verbosity: 1

# ===========================================
# INVENTORY CONFIGURATION
# ===========================================

inventory_name: "Managed Infrastructure"
inventory_description: "POC managed nodes accessible via jump host"

group_name: "managed_nodes"
group_description: "All managed nodes for automation"

# Global inventory variables
inventory_variables:
  ansible_python_interpreter: "/usr/bin/python3"
  ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  jump_host: "${jump_aap_ip}"
  environment: "poc"

# ===========================================
# EXECUTION ENVIRONMENT
# ===========================================

execution_environment:
  name: "Default EE"
  description: "Default execution environment for POC"
  image: "quay.io/ansible/automation-hub-ee:latest"
  pull: "missing"